Updating the Fine tuning tutorial
deepset-ai/haystack-tutorials pull request #124
Opened 2023-02-15 13:08 UTC by TuanaCelik

In this PR I simplify the fine-tuning tutorial and _only_ focus on the fine tuning task. I propose that we have a _separate_ tutorial for model distillation.

Before merging this PR:
1. We need to make sure that telemetry registers the correct tutorial with the new dataset download step
2. We should also include the separate distillation tutorial within this PR

2023-02-15 13:09 UTC, TuanaCelik commented
@bilgeyucel and @agnieszka-m - I am adding you as reviewers so that we first review the new content. The PR will stay open until we fix 1 and 2 in the PR comment

2023-03-14 12:24 UTC, agnieszka-m requested changes

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +- **Goal**: After completing this tutorial, you will have learned how to fine-tune a pretrained Reader model with your own data.
I think it's "on your own data", not "with"

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
>  ## Fine-tune your model
Fine-Tune Your Model

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +1. Initialize a `Reader` with the model you would like to finetune
```suggestion
1. Initialize a `Reader` with the model to fine-tune:
```

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +2. Get SQuAD style data to be used for training. Below, you can fetch a dataset that we have already prepared.
Get SQUAD-style data for training. You can use this dataset we prepared:

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +2. Get SQuAD style data to be used for training. Below, you can fetch a dataset that we have already prepared.
Remember our voice :)

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +4. Now initialize a new reader with your fine-tuned model
```suggestion
4. Now initialize a new reader with your fine-tuned model:
```

2023-03-14 12:24 UTC, agnieszka-m commented on markdowns/02_Finetune_a_model_on_your_data.md
> +5. Finaly, try using the `new_reader` that was initialized with your fine-tuned model.
This sounds like we're unsure it's going to work. I'd rephrase: Finally, use the `new_reader` that was initialized with...

2023-10-10 11:47 UTC, bilgeyucel commented
Closing this PR for the sake of updated PR #243

2023-10-10 11:47 UTC, closed without merging