Add tutorial template
deepset-ai/haystack-tutorials pull request #65
Opened 2022-11-15 08:05 UTC by agnieszka-m

2022-11-15 15:56 UTC, brandenchan requested changes

2022-11-15 15:56 UTC, brandenchan commented on tutorials/template.ipynb
> +    "<!--- Here provide a short description of the tutorial. What does it teach? What's its expected outcome? --->"
Using this syntax in a markdown box means it doesn't get displayed. I would opt rather to not start and end with the <!--- and just have plain text in each markdown cell

2022-11-15 15:56 UTC, brandenchan commented on tutorials/template.ipynb
> +    "## Task 2"
Why don't we show them a numbered list to encourage more step by step instructions?
1.
2.
3.

2022-11-15 15:56 UTC, brandenchan commented on tutorials/template.ipynb
> +    "# Next Steps\n",
I think it would make more sense to have this at header level 2

2022-11-16 08:42 UTC, brandenchan approved these changes
LGTM

2022-11-16 12:30 UTC, TuanaCelik approved these changes
Looks good to me.
Just a note: Do you already want to add the 'Prerequisites' section to the template now? Or would you rather wait for us to define how we do it ourselves and adding it in here once that's established? 
Ok either way, just wanted to point out. Will approve for now.

2022-11-16 13:09 UTC, agnieszka-m commented
@TuanaCelik I'll remove the prereqs section, I added it before finding out what your plan for it was and forgot to remove it after that.

2022-11-16 13:09 UTC, merged